[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
    "streamlit>=1.46.1",
    "pandas>=2.0.0",
    "opencv-python-headless>=4.11.0.86",
]
